name: DeepACSA
channels:
  - defaults
dependencies:
  - python=3.8
  - pip=20.3.3
  - tk=8.6.10
  - pip:
    - jupyter==1.0.0
    - Keras==2.4.3
    - matplotlib==3.3.4
    - numpy==1.19.5
    - opencv-contrib-python==4.5.1.48
    - pandas==1.1.2
    - Pillow==8.1.0
    - scikit-image==0.18.1
    - scikit-learn==0.24.1
    - tensorflow==2.4.0
    - tqdm==4.56.2
    - openpyxl==3.0.6
    - h5py==2.10.0